version: 2.0
jobs:
 build:
   docker:
     - image: circleci/ruby:2.3.6-stretch
   steps:
     - checkout
     - run:
         name: Install build tools so we can install Gems
         command: |
           apt-get update && apt-get install -y --no-install-recommends \
             build-essential \
             libpq-dev \
             libxml2-dev \
             libxslt1-dev \
           && rm -rf /var/lib/apt/lists/* \
           && apt-get clean \
           && apt-get purge
     - run: bundle install
     - run: bundle exec rails db:create db:schema:load
     - run: bundle exec rspec