version: 2.0
jobs:
 build:
   docker:
     - image: circleci/ruby:2.3.6-stretch
   steps:
     - checkout
     - restore_cache:
               keys:
                 - deps-{{ checksum "Gemfile.lock" }}
     - run: bundle install --path vendor/bundle
     - save_cache:
               key: deps-{{ checksum "Gemfile.lock" }}
               paths:
                 - "vendor/bundle"
     - run: bundle exec rails db:migrate
     - run: bundle exec rspec